# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: testsuite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy: { matrix: { node_version: [10.x] } }
    steps:
      - uses: actions/setup-env
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy: { matrix: { node_version: [10.x] } }
    steps:
      - uses: actions/setup-env
      - run: npm run test
